/**
 * Curated, serializable presets that demonstrate the available synthesis
 * modes and pattern possibilities.
 *
 * @module factory-presets
 */

/**
 * @typedef {object} FactoryPreset
 * @property {string} id
 * @property {string} name
 * @property {string} emoji
 * @property {string} tagline
 * @property {string} accentGradient
 * @property {true} isFactory
 * @property {Record<string, unknown>} settings
 */

/** @type {ReadonlyArray<FactoryPreset>} */
export const FACTORY_PRESETS = Object.freeze([
    {
        id: "factory-synthwave",
        name: "Classic Synthwave",
        emoji: "🌆",
        tagline: "Stranger Things, Kavinsky",
        accentGradient: "from-orange-500 to-pink-500",
        isFactory: true,
        settings: {
            bpm: 128,
            swing: 0,
            baseNotes: ["C4", "E4", "G4", "B4"],
            direction: "up",
            interval: "16n",
            octaveShift: 0,
            octaveRange: 2,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "major",
            synthType: "synth",
            waveform: "sawtooth",
            envAttack: 0.01,
            envDecay: 0.2,
            envSustain: 0.4,
            envRelease: 0.4,
            filterCutoff: 4500,
            filterResonance: 2,
            delayMix: 0.25,
            reverbMix: 0.35,
            loopCount: 4,
        },
    },
    {
        id: "factory-ambient",
        name: "Ambient Dreamscape",
        emoji: "✨",
        tagline: "Brian Eno, atmospheric pads",
        accentGradient: "from-teal-400 to-indigo-500",
        isFactory: true,
        settings: {
            bpm: 85,
            swing: 0.1,
            baseNotes: ["C4", "G4", "C5", "D5"],
            direction: "upDown",
            interval: "8n",
            octaveShift: 0,
            octaveRange: 2,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "lydian",
            synthType: "fmSynth",
            waveform: "sine",
            harmonicity: 2.0,
            modulationIndex: 5.0,
            envAttack: 0.1,
            envDecay: 0.6,
            envSustain: 0.7,
            envRelease: 1.2,
            filterCutoff: 3000,
            filterResonance: 1.5,
            delayMix: 0.45,
            reverbMix: 0.65,
            loopCount: 4,
        },
    },
    {
        id: "factory-cyberpunk",
        name: "Cyberpunk Bassline",
        emoji: "⚡",
        tagline: "Dark synth, driving bass",
        accentGradient: "from-yellow-400 to-red-500",
        isFactory: true,
        settings: {
            bpm: 140,
            swing: 0,
            baseNotes: ["C2", "C3", "D#2", "G2"],
            direction: "octaveCycle",
            interval: "16n",
            octaveShift: -1,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "minor",
            synthType: "monoSynth",
            waveform: "sawtooth",
            monoCutoff: 1200,
            monoOctaves: 3,
            monoQ: 4,
            driveMix: 0.4,
            envAttack: 0.005,
            envDecay: 0.15,
            envSustain: 0.1,
            envRelease: 0.2,
            filterCutoff: 2200,
            filterResonance: 4.0,
            delayMix: 0.15,
            reverbMix: 0.2,
            loopCount: 4,
        },
    },
    {
        id: "factory-harp",
        name: "Plucked Acoustic Harp",
        emoji: "🪕",
        tagline: "Organic, delicate strings",
        accentGradient: "from-amber-400 to-emerald-500",
        isFactory: true,
        settings: {
            bpm: 110,
            swing: 0.05,
            baseNotes: ["D4", "F#4", "A4", "C#5"],
            direction: "randomWalk",
            interval: "16n",
            octaveShift: 0,
            octaveRange: 2,
            scaleQuantize: true,
            scaleRoot: "D",
            scaleType: "major",
            synthType: "pluckSynth",
            waveform: "sine",
            pluckDampening: 5000,
            pluckResonance: 0.95,
            envAttack: 0.001,
            envDecay: 0.5,
            envSustain: 0.0,
            envRelease: 0.8,
            filterCutoff: 6000,
            filterResonance: 1.0,
            delayMix: 0.2,
            reverbMix: 0.5,
            loopCount: 4,
        },
    },
    {
        id: "factory-chiptune",
        name: "Chiptune Nostalgia",
        emoji: "🕹️",
        tagline: "8-bit NES, arcade arps",
        accentGradient: "from-cyan-400 to-blue-600",
        isFactory: true,
        settings: {
            bpm: 150,
            swing: 0,
            baseNotes: ["C4", "E4", "G4", "C5"],
            direction: "upDownRepeat",
            interval: "32n",
            octaveShift: 0,
            octaveRange: 2,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "majorPentatonic",
            synthType: "synth",
            waveform: "square",
            dutyCycle: 0.5,
            envAttack: 0.001,
            envDecay: 0.08,
            envSustain: 0.2,
            envRelease: 0.05,
            filterCutoff: 8000,
            filterResonance: 0.5,
            delayMix: 0.1,
            reverbMix: 0.15,
            loopCount: 4,
        },
    },
    {
        id: "factory-neosoul",
        name: "Jazzy Neo-Soul",
        emoji: "🎹",
        tagline: "Warm chorus, mellow chords",
        accentGradient: "from-purple-400 to-pink-600",
        isFactory: true,
        settings: {
            bpm: 92,
            swing: 0.35,
            baseNotes: ["D4", "F4", "A4", "C5", "E5"],
            direction: "up",
            interval: "8n",
            octaveShift: 0,
            octaveRange: 2,
            scaleQuantize: true,
            scaleRoot: "D",
            scaleType: "dorian",
            synthType: "duoSynth",
            waveform: "sine",
            duoHarm: 1.5,
            duoVibrato: 0.3,
            chorusMix: 0.3,
            envAttack: 0.02,
            envDecay: 0.3,
            envSustain: 0.5,
            envRelease: 0.6,
            filterCutoff: 3800,
            filterResonance: 1.8,
            delayMix: 0.25,
            reverbMix: 0.4,
            loopCount: 4,
        },
    },
]);
