/**
 * Curated, serializable presets that demonstrate the available synthesis
 * modes and pattern possibilities.
 *
 * @module factory-presets
 */

/** @typedef {import("../core/settings-contract.js").ArpeggiatorSettings} ArpeggiatorSettings */

/**
 * @typedef {object} FactoryPreset
 * @property {string} id
 * @property {string} name
 * @property {string} emoji
 * @property {string} tagline
 * @property {string} accentGradient
 * @property {true} isFactory
 * @property {Partial<ArpeggiatorSettings>} settings
 */

/** @type {ReadonlyArray<FactoryPreset>} */
export const FACTORY_PRESETS = Object.freeze([
    {
        id: "factory-synthwave",
        name: "Classic Synthwave",
        emoji: "🌆",
        tagline: "Stranger Things, Kavinsky",
        accentGradient: "from-orange-500 to-pink-500",
        isFactory: true,
        settings: {
            bpm: 128,
            swing: 0,
            baseNotes: ["A2", "E3", "A3", "C4", "E4", "G4", "A4", "B4"],
            direction: "up",
            interval: "16n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "A",
            scaleType: "minor",
            synthType: "synth",
            waveform: "sawtooth",
            envAttack: 0.01,
            envDecay: 0.2,
            envSustain: 0.4,
            envRelease: 0.4,
            filterCutoff: 4500,
            filterResonance: 2,
            delayMix: 0.25,
            reverbMix: 0.35,
            loopCount: 4,
        },
    },
    {
        id: "factory-ambient",
        name: "Ambient Dreamscape",
        emoji: "✨",
        tagline: "Brian Eno, atmospheric pads",
        accentGradient: "from-teal-400 to-indigo-500",
        isFactory: true,
        settings: {
            bpm: 85,
            swing: 0.1,
            baseNotes: ["C3", "G3", "D4", "E4", "G4", "B4", "D5"],
            direction: "upDown",
            interval: "8n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "lydian",
            synthType: "fmSynth",
            waveform: "sine",
            harmonicity: 2.0,
            modulationIndex: 5.0,
            envAttack: 0.1,
            envDecay: 0.6,
            envSustain: 0.7,
            envRelease: 1.2,
            filterCutoff: 3000,
            filterResonance: 1.5,
            delayMix: 0.45,
            reverbMix: 0.65,
            loopCount: 4,
        },
    },
    {
        id: "factory-cyberpunk",
        name: "Cyberpunk Bassline",
        emoji: "⚡",
        tagline: "Dark synth, driving bass",
        accentGradient: "from-yellow-400 to-red-500",
        isFactory: true,
        settings: {
            bpm: 140,
            swing: 0,
            baseNotes: ["C2", "C3", "D#2", "G2"],
            direction: "octaveCycle",
            interval: "16n",
            octaveShift: -1,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "minor",
            synthType: "monoSynth",
            waveform: "sawtooth",
            monoCutoff: 1200,
            monoOctaves: 3,
            monoQ: 4,
            driveMix: 0.4,
            envAttack: 0.005,
            envDecay: 0.15,
            envSustain: 0.1,
            envRelease: 0.2,
            filterCutoff: 2200,
            filterResonance: 4.0,
            delayMix: 0.15,
            reverbMix: 0.2,
            loopCount: 4,
        },
    },
    {
        id: "factory-harp",
        name: "Plucked Acoustic Harp",
        emoji: "🪕",
        tagline: "Organic, delicate strings",
        accentGradient: "from-amber-400 to-emerald-500",
        isFactory: true,
        settings: {
            bpm: 110,
            swing: 0.05,
            baseNotes: ["D3", "F#3", "A3", "C#4", "D4", "F#4", "A4", "C#5"],
            direction: "randomWalk",
            interval: "16n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "D",
            scaleType: "major",
            synthType: "pluckSynth",
            waveform: "sine",
            pluckDampening: 5000,
            pluckResonance: 0.95,
            envAttack: 0.001,
            envDecay: 0.5,
            envSustain: 0.0,
            envRelease: 0.8,
            filterCutoff: 6000,
            filterResonance: 1.0,
            delayMix: 0.2,
            reverbMix: 0.5,
            loopCount: 4,
        },
    },
    {
        id: "factory-chiptune",
        name: "Chiptune Nostalgia",
        emoji: "🕹️",
        tagline: "8-bit NES, arcade arps",
        accentGradient: "from-cyan-400 to-blue-600",
        isFactory: true,
        settings: {
            bpm: 150,
            swing: 0,
            baseNotes: ["C4", "G4", "C5", "E5", "G5", "E5"],
            direction: "upDownRepeat",
            interval: "32n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "majorPentatonic",
            synthType: "synth",
            waveform: "square",
            dutyCycle: 0.5,
            envAttack: 0.001,
            envDecay: 0.08,
            envSustain: 0.2,
            envRelease: 0.05,
            filterCutoff: 8000,
            filterResonance: 0.5,
            delayMix: 0.1,
            reverbMix: 0.15,
            loopCount: 4,
        },
    },
    {
        id: "factory-neosoul",
        name: "Jazzy Neo-Soul",
        emoji: "🎹",
        tagline: "Warm chorus, mellow chords",
        accentGradient: "from-purple-400 to-pink-600",
        isFactory: true,
        settings: {
            bpm: 92,
            swing: 0.35,
            baseNotes: ["D3", "A3", "C4", "F4", "A4", "C5", "E5"],
            direction: "up",
            interval: "8n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "D",
            scaleType: "dorian",
            synthType: "duoSynth",
            waveform: "sine",
            duoHarm: 1.5,
            duoVibrato: 0.3,
            chorusMix: 0.3,
            envAttack: 0.02,
            envDecay: 0.3,
            envSustain: 0.5,
            envRelease: 0.6,
            filterCutoff: 3800,
            filterResonance: 1.8,
            delayMix: 0.25,
            reverbMix: 0.4,
            loopCount: 4,
        },
    },
    {
        id: "factory-lofi-beats",
        name: "Lo-Fi Chillhop",
        emoji: "☕",
        tagline: "Mellow Rhodes chords, vinyl flutter",
        accentGradient: "from-amber-600 to-rose-700",
        isFactory: true,
        settings: {
            bpm: 76,
            swing: 0.35,
            baseNotes: ["C3", "G3", "A#3", "D#4", "G4", "A#4", "D5"],
            direction: "upDown",
            interval: "8n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "minor",
            synthType: "synth",
            waveform: "sine",
            gateRatio: 1.0,
            envAttack: 0.26,
            envDecay: 0.55,
            envSustain: 0.37,
            envRelease: 2.07,
            filterCutoff: 1350,
            filterResonance: 1.0,
            driveMix: 0.11,
            chorusMix: 0.64,
            autoPanMix: 0.2,
            delayMix: 0.35,
            reverbMix: 0.5,
            postGain: -6,
            loopCount: 4,
        },
    },
    {
        id: "factory-acid",
        name: "Acid 303 Squelch",
        emoji: "🧪",
        tagline: "Resonant squelch, driving rave",
        accentGradient: "from-lime-400 to-emerald-600",
        isFactory: true,
        settings: {
            bpm: 132,
            swing: 0.05,
            baseNotes: ["A2", "C3", "D3", "G3"],
            direction: "octaveCyclePingPong",
            interval: "16n",
            octaveShift: -1,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "A",
            scaleType: "minor",
            synthType: "monoSynth",
            waveform: "sawtooth",
            monoCutoff: 800,
            monoOctaves: 4.5,
            monoQ: 10,
            driveMix: 0.45,
            envAttack: 0.005,
            envDecay: 0.18,
            envSustain: 0.1,
            envRelease: 0.2,
            filterCutoff: 3200,
            filterResonance: 6.0,
            delayMix: 0.25,
            reverbMix: 0.2,
            loopCount: 4,
        },
    },
    {
        id: "factory-berlin",
        name: "Cosmic Sequencer",
        emoji: "🌌",
        tagline: "Tangerine Dream, hypnotic space",
        accentGradient: "from-indigo-500 to-cyan-400",
        isFactory: true,
        settings: {
            bpm: 124,
            swing: 0,
            baseNotes: ["C3", "D#3", "G3", "A#3", "C4", "A#3", "G3", "F3"],
            direction: "upDown",
            interval: "16n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "minor",
            synthType: "synth",
            waveform: "sawtooth",
            gateRatio: 0.7,
            envAttack: 0.005,
            envDecay: 0.14,
            envSustain: 0.15,
            envRelease: 0.2,
            filterCutoff: 2400,
            filterResonance: 3.5,
            driveMix: 0.1,
            delayMix: 0.5,
            reverbMix: 0.45,
            loopCount: 4,
        },
    },
    {
        id: "factory-percussion",
        name: "Glitch Marimba",
        emoji: "🪵",
        tagline: "Organic wooden mallets, acoustic bounce",
        accentGradient: "from-emerald-400 to-teal-700",
        isFactory: true,
        settings: {
            bpm: 118,
            swing: 0.1,
            baseNotes: ["C3", "G3", "C4", "D4", "E4", "G4", "A4"],
            direction: "randomCycle",
            interval: "16n",
            octaveShift: 0,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "C",
            scaleType: "majorPentatonic",
            synthType: "pluckSynth",
            waveform: "sine",
            pluckDampening: 2500,
            pluckResonance: 0.75,
            pluckNoise: 0.8,
            envAttack: 0.001,
            envDecay: 0.25,
            envSustain: 0.0,
            envRelease: 0.4,
            filterCutoff: 4500,
            filterResonance: 1.0,
            delayMix: 0.2,
            reverbMix: 0.35,
            loopCount: 4,
        },
    },
    {
        id: "factory-darkwave",
        name: "Gothic Darkwave",
        emoji: "🦇",
        tagline: "Coldwave chorus, sinister bass pulse",
        accentGradient: "from-purple-600 to-slate-800",
        isFactory: true,
        settings: {
            bpm: 134,
            swing: 0,
            baseNotes: ["B1", "B2", "C3", "B2", "G2", "F#2"],
            direction: "downUp",
            interval: "16n",
            octaveShift: -1,
            octaveRange: 1,
            scaleQuantize: true,
            scaleRoot: "B",
            scaleType: "phrygian",
            synthType: "monoSynth",
            waveform: "sawtooth",
            monoCutoff: 500,
            monoOctaves: 3.5,
            monoQ: 4.5,
            driveMix: 0.4,
            chorusMix: 0.55,
            gateRatio: 0.75,
            envAttack: 0.005,
            envDecay: 0.16,
            envSustain: 0.1,
            envRelease: 0.2,
            filterCutoff: 1250,
            filterResonance: 3.5,
            delayMix: 0.25,
            reverbMix: 0.45,
            loopCount: 4,
        },
    },
]);

/**
 * Compact root chord definitions for future migration when sequential octave traversal
 * (full-sweep arpeggiation) is introduced in a dedicated engine update.
 *
 * @type {Readonly<Record<string, {octaveRange: number, baseNotes: string[]}>>}
 */
export const SEQUENTIAL_OCTAVE_PRESET_MIGRATION = Object.freeze({
    "factory-synthwave": { octaveRange: 2, baseNotes: ["A2", "C3", "E3", "G3"] },
    "factory-ambient": { octaveRange: 2, baseNotes: ["C3", "G3", "D4", "E4"] },
    "factory-harp": { octaveRange: 2, baseNotes: ["D3", "F#3", "A3", "C#4"] },
    "factory-chiptune": { octaveRange: 2, baseNotes: ["C4", "E4", "G4", "B4"] },
    "factory-neosoul": { octaveRange: 2, baseNotes: ["D3", "F3", "A3", "C4"] },
    "factory-lofi-beats": { octaveRange: 2, baseNotes: ["C3", "D#3", "G3", "A#3"] },
    "factory-percussion": { octaveRange: 2, baseNotes: ["C3", "E3", "G3", "A3"] },
});
