#!/usr/bin/env bash
#
# scripts/generate-maskable-svg.sh
#
# Generates the PWA maskable SVG icon from the standard PWA SVG icon.
# This script uses perl and standard shell utilities to perform the transformation.
#

set -euo pipefail

# Define variables for paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ICON_DIR="${ROOT_DIR}/images/icons"

SOURCE_SVG="${ICON_DIR}/pwa-icon.svg"
TARGET_SVG="${ICON_DIR}/pwa-icon-maskable.svg"

echo "Reading source SVG: ${SOURCE_SVG}"

if [ ! -f "${SOURCE_SVG}" ]; then
    echo "Error: Source SVG not found at ${SOURCE_SVG}" >&2
    exit 1
fi

# 1. Extract the <defs> block
# Reads the entire SVG file into memory (-0777) and extracts contents within <defs> tags
DEFS_CONTENT=$(perl -0777 -ne 'print $1 if /<defs>(.*?)<\/defs>/s' "${SOURCE_SVG}")

# 2. Extract inner elements (excluding the rounded background rect)
# Finds all content after the defs block and before the closing svg tag,
# then strips the background <rect> element with rx="112".
INNER_CONTENT=$(perl -0777 -ne '
  if (/<defs>.*?<\/defs>(.*?)<\/svg>/s) {
    $c = $1;
    $c =~ s/<rect[^>]*rx="112"[^>]*\/>\s*//gi;
    print $c;
  }
' "${SOURCE_SVG}")

# 3. Format inner content with indents
# Prepend 4 spaces to each line of the inner content for clean SVG formatting
FORMATTED_CONTENT=$(echo "${INNER_CONTENT}" | sed 's/^/    /')

# 4. Generate target file
# Creates the final maskable SVG with a full-bleed background and scaled/positioned contents
cat <<EOF >"${TARGET_SVG}"
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="Web Arpeggiator maskable icon">
  <!--
    Web Arpeggiator Maskable Icon (Concept 2: Step Sequencer Matrix)

    WARNING: This file is programmatically generated from pwa-icon.svg.
    Do not edit this file directly. Modify pwa-icon.svg and re-run scripts/generate-pwa-assets.sh.
  -->
  <defs>
    ${DEFS_CONTENT}
  </defs>

  <!-- Full bleed square background to cover OS maskable safe areas -->
  <rect x="0" y="0" width="512" height="512" fill="url(#bg)" />

  <!--
    Programmatically generated group content:
    - Scaled to 80% around original center (256, 261)
    - Shifted upwards by 25px (yielding new target center of 256, 231)
  -->
  <g transform="translate(256, 231) scale(0.8) translate(-256, -261)">
${FORMATTED_CONTENT}
  </g>
</svg>
EOF

echo "Successfully generated maskable SVG: ${TARGET_SVG}"
